### ISSUE TITLE
[Feature Request] Procgen integration

### ISSUE THREAD

**Issue by mavenlin** [sail-sg/envpool#10]
https://github.com/openai/procgen

Env List:

- bigfish
- bossfight
- caveflyer
- chaser
- climber
- coinrun
- dodgeball
- fruitbot
- heist
- jumper
- leaper
- maze
- miner
- ninja
- plunder
- starpilot

Road Map:

- [ ] Get comfortable with current codebase, go through https://envpool.readthedocs.io/en/latest/pages/env.html and add a toy environment by yourself locally;
- [ ] Download Procgen and run on your local machine, try with different env settings and see the actual behavior;
- [ ] Go through their source code https://github.com/openai/procgen/tree/master/procgen/src, understand the code structure and where we can bind EnvPool APIs (I think the entry is vecgame.cpp);
- [ ] Integrate only one game and let it work;
- [ ] Add some unit tests (good to submit the first PR here);
- [ ] Integrate other games (submit another PR) and related tests.

Resources: 
- https://openai.com/blog/procgen-benchmark/

**Comment by Trinkle23897** [comment]
Of course! We are going to integrate procgen without their vector env.
