### ISSUE TITLE
[BUG] Misalignment on Humanoid-v3

### ISSUE THREAD

**Issue by Trinkle23897** [sail-sg/envpool#143]
Reported by rl_games

Initial result reported by @Benjamin-eecs

1. envpool v3 train gym v3 test
gym v3 17 step, reward \~82
envpool v3 1001 step, reward \~10000, but has variance (maybe not fix seed?)
2. gym v3 train envpool v3 test
gym v3 1000 step, reward \~6200
envpool v3 29 step, reward \~144

**Comment by yufansong** [comment]
For Humanoid env, there exists some differences in `cost` calculation: [humanoid-v3](https://github.com/openai/gym/blob/6a04d49722724677610e36c1f92908e72f51da0c/gym/envs/mujoco/humanoid_v3.py#L156), [humanoid-v4](https://github.com/openai/gym/blob/6a04d49722724677610e36c1f92908e72f51da0c/gym/envs/mujoco/humanoid_v4.py)

Also, find ant v3-v4 has bug too: [ant-v3](https://github.com/openai/gym/blob/master/gym/envs/mujoco/ant_v3.py#L129), [ant-v4](https://github.com/openai/gym/blob/master/gym/envs/mujoco/ant_v4.py#L309)
