### ISSUE TITLE
[BUG] Can't install on python 3.9 / 3.10 on macOS

### ISSUE THREAD

**Issue by nico-bohlinger** [sail-sg/envpool#153]
I tried to install envpool on python 3.9.5 and 3.10.0 with `pip install envpool` and got the following in both cases:

```
ERROR: Could not find a version that satisfies the requirement envpool (from versions: none)
ERROR: No matching distribution found for envpool
```

I haven't checked other python versions though.

**Comment by Trinkle23897** [comment]
What's the output of `pip -V`?

**Comment by nico-bohlinger** [comment]
pip 22.1.2 from /usr/local/anaconda3/envs/default395/lib/python3.9/site-packages/pip (python 3.9)

**Comment by Trinkle23897** [comment]
Which OS?

**Comment by nico-bohlinger** [comment]
macOS Catalina

**Comment by Trinkle23897** [comment]
That's the reason. We currently only provided linux wheels. Windows/macOS will be supported in a few weeks.

**Comment by nico-bohlinger** [comment]
Ahh I suspected that but I wasn't sure because I didn't find anything on OS requirements. Then I will boot up Linux, thank you for the fast support :)

**Comment by smorad** [comment]
I assume there is now MacOS support as this is marked as completed, but I don't see any wheels yet

```
pip 21.2.4 from /Users/smorad/opt/miniconda3/envs/ray/lib/python3.9/site-packages/pip (python 3.9)
MacOS Monterey 12.1
```

Should we build from source?

**Comment by Trinkle23897** [comment]
No, it's not completed.

**Comment by Trinkle23897** [comment]
Move this thread to #168.
