### ISSUE TITLE
[Feature Request] Template for private env that uses envpool as a dependency

### ISSUE THREAD

**Issue by mavenlin** [sail-sg/envpool#155]
## Motivation

It is desirable that one can develop their own env without having to work under envpool's code base. While still have the access to register the env with envpool and use the `make` function to create it. It seems already possible with our current code base, we just need a template repo.

## Solution
```python3
import envpool
import my_private_env
my_env = envpool.make("MyPrivateEnv")
```
Where `my_private_env` is developed as another package.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

cc @zhongwen

**Comment by Trinkle23897** [comment]
Can we create another repo for this template? What do you think the name of this repo?

**Comment by zhongwen** [comment]
private pool
