### ISSUE TITLE
[BUG] Transition pair misalignment in the `ppo_atari` example

### ISSUE THREAD

**Issue by fuyw** [sail-sg/envpool#174]
## Describe the bug

In the `ppo_atari` example, we sample the `action`:

https://github.com/sail-sg/envpool/blob/ea86c2b77d12aaa58725bfeb1d701e3207f11822/examples/ppo_atari/ppo.py#L236

after we receive transitions from the `train_envs`:

https://github.com/sail-sg/envpool/blob/ea86c2b77d12aaa58725bfeb1d701e3207f11822/examples/ppo_atari/ppo.py#L231

Then the tuple `(obs, act, rew, done, log_prob, value)` is added to the batch.

However, it seems that `obs = o_{t+1}`, `act = a_{t+1}`, `rew = r_t`, `done = d_t` corepond to two different timestamps.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://envpool.readthedocs.io/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Trinkle23897** [comment]
> correspond to two different timestamps.

In `gae.py` it corrects the order:

https://github.com/sail-sg/envpool/blob/ea86c2b77d12aaa58725bfeb1d701e3207f11822/examples/ppo_atari/gae.py#L41-L48
