### ISSUE TITLE
[Feature Request] Custom Environment

### ISSUE THREAD

**Issue by im-Kitsch** [sail-sg/envpool#176]
Hallo,

thanks a lot  for your excellent work. Just wonder that if we can easily wrap our customized environment inside envpool. 

It is also a very common usecase that we use modified mujoco environment or manually created toy task. 

It will be very appreciated if we have any tutorial that we can add our customized environment.

Thanks in advance

**Comment by Trinkle23897** [comment]
See [Customized C++ environment integration](https://envpool.readthedocs.io/en/latest/content/new_env.html)
