### ISSUE TITLE
[BUG] prevent using recv() without send()

### ISSUE THREAD

**Issue by im-Kitsch** [sail-sg/envpool#177]
Hello, 

just find that if I wrongly run recv() without send(), then the program will goes into like an infinite loop. 

It would very easily to occur in jupyter or interactive console or program bug. 

Would it be better to add a timeout function inside recv() function?

Best regards.

**Comment by Trinkle23897** [comment]
I don't think it's possible because, from EnvPool's perspective, it cannot predict the single env step elapsed time. It's hard to tell the difference between user's wrong calling pattern and env's slow execution speed.
