### ISSUE TITLE
[BUG] Truncation does not always trigger in `Atlantis-v5`

### ISSUE THREAD

**Issue by vwxyzjn** [sail-sg/envpool#179]
## Describe the bug

Truncation does not always trigger in `Atlantis-v5`.

## To Reproduce

Download evaluation snippet [here](https://gist.github.com/vwxyzjn/f0868d7e56a8eea5a4a93c7467bdfd69) and the trained model [here](https://wandb.ai/costa-huang/cleanRL/runs/83acpxnz/files/checkpoint_0). Put them at the same folder, and run `python ppo_atari_eval.py`. The core snippet looks like

```python
    envs = envpool.make("Atlantis-v5", ..., num_envs=1)
    for e in range(3):
        global_step = 0
        next_obs = envs.reset()
        episode_returns = np.zeros(args.num_envs)
        for i in range(200000):
            global_step += args.num_envs
            action, logprob, value, key = get_action_and_value(agent_state, next_obs, key)
            next_obs, reward, next_done, info = envs.step(np.array(action))
            episode_returns += reward
            if info["terminated"].sum() > 0 or info["TimeLimit.truncated"].sum() > 0:
                break
            
        print(f"step {global_step}, episode return {episode_returns.mean():.2f}")
```

```bash
python ppo_atari_eval.py
step 108000, episode return 6214.00
step 200000, episode return 11432.00
step 124003, episode return 7115.00
```

## Expected behavior

The step should never reach 200000. The truncation limit of 108000 should always trigger.

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import envpool, numpy, sys
print(envpool.__version__, numpy.__version__, sys.version, sys.platform)
```
```
>>> print(envpool.__version__, numpy.__version__, sys.version, sys.platform)
0.6.3 1.21.6 3.9.5 (default, Jul 19 2021, 13:27:26) 
[GCC 10.3.0] linux
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://envpool.readthedocs.io/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Trinkle23897** [comment]
It's because the current implementation has two copies of `elapsed_step`: one is from atari env, and the other one is from base env (for convenience of other 3rd-party env). When `episodic_life=True`, these two values are mismatched (`info["TimeLimit.truncated"]` is from the base env's `elapsed_step`, so it's the interval of life discount instead of the whole atari game), thus causing the above buggy behavior.
