### ISSUE TITLE
[BUG] Make bazel-test error on main branch

### ISSUE THREAD

**Issue by Benjamin-eecs** [sail-sg/envpool#182]
## Describe the bug

Make bazel-test error when clone the main branch of envpool

## To Reproduce

```bash
$ git clone https://github.com/sail-sg/envpool.git
$ make bazel-test
```

```bash
./envpool/core/xla.h:20:10: fatal error: cuda_runtime_api.h: No such file or directory
   20 | #include <cuda_runtime_api.h>
```

## Expected behavior

No error.

## Screenshots
![envpool_bug_0](https://user-images.githubusercontent.com/32269413/183054572-1ef89b43-fc0b-4663-818d-cb7d06401b25.png)

## System info

```python
0.6.3.post1 1.23.1 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] linux
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://envpool.readthedocs.io/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Trinkle23897** [comment]
You should install cuda first, e.g., `apt install cuda`.

**Comment by Benjamin-eecs** [comment]
Yes, the bazel test will run with a machine installed with cuda driver, may need to give a heads-up in the docs.

But there are some other errors acrossing core test, atari test and mujoco test. I will give a look at mujoco test error.

![envpool_bug_1](https://user-images.githubusercontent.com/32269413/183121549-078d95ed-10c6-474f-8d7f-5d89b666592b.png)

**Comment by Trinkle23897** [comment]
What does the log say?

**Comment by Benjamin-eecs** [comment]
`//envpool/core:state_buffer_queue_test`

![envpool_core_bug_0](https://user-images.githubusercontent.com/32269413/183240784-f54c4132-8b49-4416-b791-532962398e10.png)

`//envpool/atari:atari_envpool_test`

![envpool_atari_bug_0](https://user-images.githubusercontent.com/32269413/183240795-f1e2fcb2-c6d2-4b94-8bc7-ae920d33fd72.png)

`//envpool/mujoco:mujoco_dmc_suite_align_test`, `//envpool/mujoco:mujoco_dmc_suite_ext_align_test`

`dmc_finger`

![envpool_mujoco_dmc_finger_bug](https://user-images.githubusercontent.com/32269413/183240846-c702644d-632a-49f9-b372-2c04a96170b8.png)

`dmc_hopper`

![envpool_mujoco_dmc_hopper_bug](https://user-images.githubusercontent.com/32269413/183240863-4dc9cd83-8ae6-49f9-b210-a2bb98951b41.png)

`dmc_humanoid`

![envpool_mujoco_dmc_humanoid_bug](https://user-images.githubusercontent.com/32269413/183240890-66c901f8-3b38-489f-a867-18b63a5b76b4.png)

`dmc_humanoid_CMU`

![envpool_mujoco_dmc_humanoid_CMU_bug](https://user-images.githubusercontent.com/32269413/183240895-0007af68-11df-49cc-a26f-3118e0ee7564.png)

`dmc_manipulator`

![envpool_mujoco_dmc_manipulator_bug](https://user-images.githubusercontent.com/32269413/183240903-572b860e-a304-47bd-89eb-d4eb7913ede9.png)

`dmc_swimmer`

![envpool_mujoco_dmc_swimmer_bug](https://user-images.githubusercontent.com/32269413/183240907-9b1040d4-30ec-43ce-8a6e-47136e9f9086.png)

`dmc_walker`

![envpool_mujoco_dmc_walker_bug](https://user-images.githubusercontent.com/32269413/183240912-fdd536be-5329-41e9-9d15-7a9888ea8eba.png)

`//envpool/mujoco:mujoco_gym_align_test`

![envpool_mujoco_gym_bug](https://user-images.githubusercontent.com/32269413/183240944-137f9918-a1a1-4c83-8ed8-565d606e4dcf.png)

**Comment by mavenlin** [comment]
I saw these errors too when the tests are ran on GPU machine. Some are due to numerical error when running the pretrained tests. But the state buffer test error is very strange and theoretically shouldn't happen.

**Comment by Trinkle23897** [comment]
It's because if mujoco==2.2.0 vs 2.2.1

**Comment by mavenlin** [comment]
Upgrading mujoco solves all the above issues? It is strange how the state buffer queue test get affected by mujoco.

**Comment by Trinkle23897** [comment]
My experience is if we use a low computational resource machine, she test may be blocked at some time when other tests is fail or consume a lot of cpu resources. At this time you only need to run it again.
