### ISSUE TITLE
Does envpool support class environments written according to the gym standard?

### ISSUE THREAD

**Issue by jaried** [sail-sg/envpool#184]
For example, I have an environment called `MyEnv`, and I use `tianshou` to run it. Is it correct to call it in the following way?
```python
env=MyEnv()
train_envs = envpool.make(MyEnv, num_envs=args.training_num, env_type="gym")
test_envs = envpool.make(MyEnv, num_envs=args.test_num, env_type="gym")
```

**Comment by Trinkle23897** [comment]
You need to write env with C++ interface.

**Comment by jaried** [comment]
Does it not support the environment written in python?

**Comment by Trinkle23897** [comment]
Current answer is, yes. Every single line of python code requires GIL, which blocks the overall speed of EnvPool.

**Comment by jaried** [comment]
I understand. Thanks for your answer.
