### ISSUE TITLE
[Feature Request] Support for Mujoco -2 env?

### ISSUE THREAD

**Issue by cangcn** [sail-sg/envpool#190]
Dear authors,

Envpool can be a powerful tool to reduce the evaluation time for offline RL research.

Let me give an example. For IQL or CQL algorithms with Jax implementation, the time used for training on the offline dataset can be 8-12s, but it often takes about 4-6s to evaluate by interacting with the online environment. Envpool can reduce time consumption by parallelizing the evaluation. 

However, the datasets used for offline RL algorithm training (actually, the D4RL Mujoco datasets), are often generated by interacting with the Mujoco -V2 envs, which are not supported by the envpool. (For details, please refer to this issue, https://github.com/Farama-Foundation/D4RL/issues/116)

Please consider adding support for the following envs:
Walker2d-v2
HalfCheetah-v2
Hopper-v2

Finally, congratulations on your good scores at NIPS!

Best,
Chengqian

**Comment by Trinkle23897** [comment]
We won't add -v2 environment because it's almost the same as -v3 environment. cc @vwxyzjn 
Also, `mujoco_py` has been deprecated and it's not worth integrating such a buggy binary/pyx project into our codebase. It would bring us tons of tech debt.
