### ISSUE TITLE
[Feature Request] support with offline dataset (D4RL)

### ISSUE THREAD

**Issue by louieworth** [sail-sg/envpool#193]
Could you add a feature that supports offline RL research?

eg. 
```
import gym
env_name = 'hopper-medium-v2'
env = gym.make(env_name)
```

references: d4rl

**Comment by cijerezg** [comment]
Adding to this, I think it'd be great if you can the environments supported by D4RL.

**Comment by mavenlin** [comment]
I believe offline dataset is better supported by the amazing [`tf.data.Dataset`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset)
