### ISSUE TITLE
[BUG] incompatible constructor arguments when using seed >= 2**31

### ISSUE THREAD

**Issue by araffin** [sail-sg/envpool#214]
## Describe the bug

Envpool crashes at startup if a `seed >= 2**31` is passed.
The main issue is that the error message is not very informative:

## To Reproduce

```python
import envpool

seed = 2**31 # 2**31 -1 does work
envpool.make("Pendulum-v1", env_type="gym", num_envs=1, seed=seed)
```

```
    env = envpool.make(self.env_name.gym_id, env_type="gym", num_envs=n_envs, seed=self.seed)
  File "/home/antonin/miniconda3/lib/python3.7/site-packages/envpool/registration.py", line 58, in make
    spec = self.make_spec(task_id, **kwargs)
  File "/home/antonin/miniconda3/lib/python3.7/site-packages/envpool/registration.py", line 76, in make_spec
    return spec_cls(config)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. envpool.classic_control.classic_control_envpool._PendulumEnvSpec(arg0: Tuple[int, int, int, int, int, str, int, bool, int, int])

Invoked with: Config(num_envs=1, batch_size=0, num_threads=0, max_num_players=1, thread_affinity_offset=-1, base_path='envpool', seed=2147483648, gym_reset_return_info=False, max_episode_steps=200, version=1)

```

## Expected behavior

Either no crashes or a better error message.
## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

Latest envpool version: envpool==0.6.5
on linux.

```python
import envpool, numpy, sys
print(envpool.__version__, numpy.__version__, sys.version, sys.platform)
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://envpool.readthedocs.io/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Trinkle23897** [comment]
Yes that's expected behavior because internally we use int to store `seed`.

**Comment by araffin** [comment]
Thanks =)

(I was testing Envpool + RLZoo + SBX (SB3 + Jax) when it happened, I managed to get 2100+FPS for SAC on mujoco envs =): https://wandb.ai/openrlbenchmark/sbx/runs/2cgmufa8?workspace=user-araffin
SBX: https://github.com/araffin/sbx)

**Comment by Trinkle23897** [comment]
Nice! envpool==0.6.6 will increasingly improve the performance, definitely worth a try with the incoming new release!
