### ISSUE TITLE
[Feature Request] Python 3.11

### ISSUE THREAD

**Issue by araffin** [sail-sg/envpool#226]
## Motivation

Hello,

Is there any plan to release python 3.11 wheels?
That would be nice as python 3.11 already offers a nice speed boost (and pytorch/jax already support it).

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Trinkle23897** [comment]
Will do, thanks!

**Comment by Trinkle23897** [comment]
I'm currently blocked by building 3.11 on ubuntu 16.04. It says 
```
Installing Python-3.11-dev...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.pyenv/versions/3.11-dev/lib/python3.11/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
```
I follow the instruction to manually install `openssl-1.1.1s` and successfully build 3.10 on ubuntu16.04 but still didn't get work on 3.11.

**Comment by araffin** [comment]
thanks for trying =)
you should probably try with a newer Ubuntu version.

**Comment by Trinkle23897** [comment]
The reason is because manylinux_2014 wheel needs to be built on old version glibc, where Ubuntu 1604 can support it but 1804 can’t. Otherwise there may be some glibc compatibility issues when using pre-build wheel.

Also you cannot upload a wheel without auditwheel fix to pupil server. You can have a try :)

**Comment by araffin** [comment]
> The reason is because manylinux_2014 wheel needs to be built on old version glibc, where Ubuntu 1604 can support it but 1804 can’t. 

oh :/ (I don't know much about python wheels, good to know)

Thanks for releasing the pre-built wheel =)
