### ISSUE TITLE
[Feature Request] DeepMind Control Suite from pixels

### ISSUE THREAD

**Issue by qgallouedec** [sail-sg/envpool#235]
## Motivation

[The wrapper to use DMCS with gym](https://github.com/denisyarats/dmc2gym) has an interesting feature that allows you to learn directly with the rendering (pixels), and not with the state. I don't see this feature integrated in envpool. Is it planned?

## Solution

Could be an additional env kwargs:

```python
envpool.make_dm("BallInCupCatch-v1", num_envs=1, from_pixels=True)
```

Or register those envs:

```python
envpool.make_dm("BallInCupCatchImage-v1", num_envs=1)  # or BallInCupCatchFromPixels-v1, doesn't matter
```

## Alternatives

I don't any workaround to use DeepMind control suite from pixel with envpool in the current state.

## Additional context

From the [paper](https://arxiv.org/pdf/1801.00690.pdf)

> We also benchmarked a variant of D4PG that learns directly from pixel-only input, using 84 × 84 RGB frames from the 0th camera.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Trinkle23897** [comment]
#150

**Comment by qgallouedec** [comment]
I searched for "Deepmind Control Suite" and not for "dmc". Sorry for the duplicate. I close this issue, since it is in fact part of #136
