### ISSUE TITLE
[BUG]windows no have pip install envpool ERROR: No matching distribution found for envpool

### ISSUE THREAD

**Issue by xiezhipeng-git** [sail-sg/envpool#241]
## Describe the bug
windows pip install envpool
ERROR: Could not find a version that satisfies the requirement envpool (from versions: none)
ERROR: No matching distribution found for envpool

https://pypi.org/project/envpool/#files
only Linux
## To Reproduce
windows can not pip install envpool
then i try pip install .
it has error 
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      error: could not create 'build': 当文件已存在时，无法创建该文件。
      [end of output]

because already BUILD file. windows Case-insensitive
so I change envpool/BUILD file rename BUID1
then I try pip install . in envpool path
it seems setup success but 

 ```python
import envpool
print(envpool.list_all_envs())
```
envpool.list_all_envs() = []

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)  pip 23.0 
 * Python version 3.9.13

**Comment by Karlheinzniebuhr** [comment]
Same issue here on win10

```
pip install envpool
ERROR: Could not find a version that satisfies the requirement envpool (from versions: none)
ERROR: No matching distribution found for envpool
```

**Comment by mavenlin** [comment]
As we don't have a plan for windows, will close this issue.
