### ISSUE TITLE
[Feature Request]how to show envpool games 

### ISSUE THREAD

**Issue by xiezhipeng-git** [sail-sg/envpool#253]
## Motivation

I want to see the gym running state

## Solution

Give me a function to show game render

## Alternatives

show running game or save gifs

**Comment by Trinkle23897** [comment]
unfortunately you cannot directly call `.render()` function. You need to save the original observation image (if possible) to either png/jpg format or gif format. Here is an example for atari:

https://github.com/sail-sg/envpool/blob/35f7f28e9d9fa33ee21a5f7018a34c370360d198/envpool/atari/atari_pretrain_test.py#L75-L79
