### ISSUE TITLE
[Feature Request] Multiple EnvPool Instance Sharing the Same ThreadPool

### ISSUE THREAD

**Issue by vwxyzjn** [sail-sg/envpool#261]
## Motivation

Would it be possible to share the same thread pool with multiple EnvPool instances, so as to have an API that looks like

```
import envpool

threadpool = envpool.threadpool(num_threads=50)
envs1 = envpool.make("Breakout-v5", num_envs=170, env_type="gym", threadpool=threadpool)
envs2 = envpool.make("Pong-v5", num_envs=170, env_type="gym", threadpool=threadpool)
```

This API would allow for more flexible use cases, such as 1) using actor threads, each of which maintains an envpool instance that shares the same threadpool, 2) training multi-tasks agent that can play `Breakout-v5` and `Pong-v5` at the same time, 3) create double buffering API simpler for the learning algorithm, in which the env steps are the same across subenvs unlike the envpool async API.

@jsuarez5341 proposes the following  alternative double buffering API
```python
threadpool = envpool.threadpool(num_threads=60)
buffers = []
for i in range(num_buffers):
    envs = envpool.make(env_id, env_type="gym", num_envs=num_envs, threadpool=threadpool)
    buffers.append(envs)
obs = torch.zeros((num_steps, num_buffers, num_envs) + envs.single_observation_space.shape).to(device)
next_obs, next_done, env_ids = [], [], []
for envs in buffers:
    envs.async_reset()
    o, _, _, info = envs.recv()
    next_obs.append(torch.Tensor(o).to(device))
    next_done.append(torch.zeros((num_envs,)).to(device))
    env_ids.append(info['env_id'])

for step in range(0, num_steps):
    for buf, envs in enumerate(buffers):
        global_step += 1 * num_envs
        env_id = env_ids[buf]
        obs[step, buf][env_id] = next_obs[buf]
        dones[step, buf][env_id] = next_done[buf]
        o, r, done, info = envs.recv()
        next_obs[buf] = torch.Tensor(o).to(device)
        next_done[buf] = torch.Tensor(done).to(device)
        env_ids[buf] = info['env_id']
        env_id = env_ids[buf]
        rewards[step, buf][env_id] = torch.tensor(r).to(device).view(-1)
```

### Additional distributed RL consideration

While async API works really well already, I have come across difficulties in some actor-learner setups. For example, the GAE calculation code for async API below would not work if the I partitions `values`, `rewards`, and `dones` to separate devices because partitioning requires all the envs to have the same number of steps. As a result, the learner devices could be bottlenecked by calculating the GAE from a single device.

https://github.com/sail-sg/envpool/blob/51f468604fd0f21ae19a970e88f893433dc4b4ec/examples/ppo_atari/gae.py#L23-L49

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by mavenlin** [comment]
@vwxyzjn I like this idea a lot, I believe the double buffer could be pushed further to multiple buffers, which will close the gap to fully async code even more. 

The benefits you mentioned above are very solid.

- Ease the problem of integration with downstream RL algorithm.
- Enable multiple different envpool instances (could be running different envs) to share the threadpool.

**Comment by vwxyzjn** [comment]
Thanks @mavenlin! Is there any chance you could build a wheel? I'd love to give it a try.

**Comment by mavenlin** [comment]
@vwxyzjn Sure, I've triggered wheel build here
https://github.com/sail-sg/envpool/actions/runs/5130115723
Check the artifacts when this is done.

The usage example can be find in
https://github.com/sail-sg/envpool/blob/shared_thread_pool/envpool/atari/api_test.py#L328

**Comment by vwxyzjn** [comment]
Sorry for the delay @mavenlin. Thanks for the artifact! I found the new API is very slightly faster (pink curve) in my particular setting :) Given the substantial change, maybe it's not worth it yet. 

<img width="958" alt="image" src="https://github.com/sail-sg/envpool/assets/5555347/a7fae337-39c3-4c80-b32d-f05b40b758f2">

**Comment by mavenlin** [comment]
Sure, I'll keep this branch, maybe we can find other usage of this in the future.
