### ISSUE TITLE
[BUG] In Atari, noop_max=0 leads to a segmentation fault

### ISSUE THREAD

**Issue by mklissa** [sail-sg/envpool#262]
## Describe the bug

A value of `noop_max=0` leads to segmentation fault when creating an Atari environment.

## To Reproduce

Running this minimal code with version `envpool==0.8.1` leads to the error.

```python
import envpool


envs = envpool.make(
    "Pong-v5",
    env_type="gym",
    noop_max=0,
    num_envs=1,
)

envs.reset()
```

```bash
Segmentation fault
```

## Expected behavior
If I understand correctly the module, `random_noop=0` should be an option as `repeat_action_probability=0.25` (sticky actions) does a better job at stochasticity as per Machado et al. 2017. It is also the default in the high quality Dopamine implementation of DQN-style aglorithms for Atari.

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import envpool, numpy, sys
print(envpool.__version__, numpy.__version__, sys.version, sys.platform)

0.8.1 1.24.2 3.8.2 (default, May 15 2020, 20:21:35) 
[GCC 9.3.0] linux
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)
- [X] I have read the [documentation](https://envpool.readthedocs.io/) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Trinkle23897** [comment]
https://github.com/sail-sg/envpool/issues/234
