### ISSUE TITLE
Cannot reproduce benchmark FPS for Mujoco on DGX A100

### ISSUE THREAD

**Issue by nik7273** [sail-sg/envpool#266]
Hi, I've been trying to reproduce the same results as the ones included in your benchmark for Mujoco, but my numbers are significantly slower. I'm running the same benchmarking commands+arguments as seen on your [benchmarks](https://envpool.readthedocs.io/en/latest/content/benchmark.html) page on a DGX A100 with 256 CPU cores and 8 NUMA cores.

Here are the rough numbers I've been getting for different configurations:
sync: ~175000
async: ~250000
numa+async: ~375000

As you can see, these numbers are significantly lower than expected.

Is there anything about my computing configuration that I need to check or do you have any tips for how I can better reproduce your numbers? Let me know if you need more information and I'll be happy to provide it.

**Comment by nik7273** [comment]
Never mind, I realized that I was using the wrong parameters. The instructions on the page should be a little more explicit. I think it would be useful to describe exactly which parameters were used to arrive at the given numbers. The plot states that you tested performance up to batch size ~256 but did not describe the corresponding number of environments (which is fine but not ideal -- the rule of thumb to use ~2.5-3x made my performance close enough). The "testing method and command" section seems to list numbers for testing on a laptop only, but I guess it should just be explicitly stated that those are the numbers for the laptop, because people like me will probably blindly apply commands without common sense (oops)! Sorry for the unnecessary issue.

**Comment by Trinkle23897** [comment]
would you like to submit a PR to make it better?

**Comment by nik7273** [comment]
I'd be happy to if you happen to have the exact parameters that were used to get your numbers, because I haven't found the right values to reproduce them fully (my performance on numa + async goes up to around 2M, which is close in magnitude to but still less than 3M). I can just add a table if you do, and then some additional clarifying text around the stuff that confused me.
