### ISSUE TITLE
How to compile new environment into EnvPool

### ISSUE THREAD

**Issue by quark2019** [sail-sg/envpool#28]
After following to  [Add New Environment into EnvPool](https://envpool.readthedocs.io/en/latest/pages/env.html), I've finished coding on a new self-define Env.
How to compile the codes and add new env into EnvPool? 
([https://envpool.readthedocs.io/en/latest/pages/build.html](https://envpool.readthedocs.io/en/latest/pages/build.html) shows how to build EnvPool, but not build new Env.)

eg, how to compile the example `Dummy` Env into EnvPool?

Please take some time to update [https://envpool.readthedocs.io/en/latest/pages/env.html](https://envpool.readthedocs.io/en/latest/pages/env.html), thanks!

**Comment by Trinkle23897** [comment]
I'm trying to serve #25 as a minimal example to show how to integrate new environments. After that pull request merges, I'll update the documentation accordingly. Stay tuned!

**Comment by AlessandroZavoli** [comment]
Thank you for this amazing work!
I had the same problem, I don't understand how to compile the code and where to put it.
Is it necessary to clone envpool and install it from scratch? Or can it be used via pip install envpool?

Best,
Alessandro

**Comment by Trinkle23897** [comment]
https://envpool.readthedocs.io/en/latest/pages/env.html

If you want to integrate your new env into envpool, it's necessary to build from scratch (because we use Bazel build system to compile a binary .so file).

**Comment by AlessandroZavoli** [comment]
Thanks! Is the best practice fork the project and add the new environment in the envpool folder?
If so, you might consider adding this sentence on top of that page.

**Comment by Trinkle23897** [comment]
Will do that, thanks for the suggestion!
