### ISSUE TITLE
Set values for action in C++

### ISSUE THREAD

**Issue by AcademicWaste** [sail-sg/envpool#280]
Hi,
I wonder how can I set values for action within C++. For example, I have defined 
```
  template <typename Config>
  static decltype(auto) ActionSpec(const Config& conf)
  {
    int num_actions = 5;
    vector<int> lower_bounds(num_actions, {0});
    vector<int> upper_bounds(num_actions, {INT_MAX});
    return MakeDict(
        "action"_.Bind(Spec<int>({num_actions}, {lower_bounds, upper_bounds})));
  }
```
for the action spec.

I want to do some manually inputs for specifying the action. For example, do something like:
```
Action action;
for(int i = 0; i<5; i++){
    action["action"_][i] = i;
}
```

Is there a way to do that? Thanks!

**Comment by Trinkle23897** [comment]
like this? https://github.com/sail-sg/envpool/blob/47ad258713ec89f874819ed8318ed77ae4d4b1e8/envpool/atari/atari_env_test.cc#L127

**Comment by AcademicWaste** [comment]
> like this?
> 
> https://github.com/sail-sg/envpool/blob/47ad258713ec89f874819ed8318ed77ae4d4b1e8/envpool/atari/atari_env_test.cc#L127

Yes! Thank you!
