### ISSUE TITLE
[Feature Request] async_reset supports multiple calls until getting obs from all envs

### ISSUE THREAD

**Issue by LuciusMos** [sail-sg/envpool#63]
## Motivation

In my project, I set all env's initial state to the ``obs`` returned from ``step``(sync mode) or ``recv``(async mode). After the initialization will I start training or evaluation. Everything is ok in sync mode. However in async mode, for example, ``env_num`` is 16 and ``batch_size`` is 8, I call ``async_reset`` once and get 8 envs' initial state. If I call ``async_reset`` again, there will be an error, so that I cannot initialize all envs' initial state at the beginning.

## Solution

I can call ``async_reset`` multiple times to get all envs' observation. In the example, the first call will reset 8 envs, and the second call will reset another 8 envs.

## Alternatives

I think it is ok that I can call ``reset``(sync mode) in aysnc mode, and ``reset`` functions exactly as in sync mode.

## Additional context

No.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Trinkle23897** [comment]
Actually the first version of EnvPool has two separated threadpool, one for reset and one for step, and that can satisfy the aforementioned requirement. @mavenlin decided to change the pipeline to the current style, which is only one threadpool for all executions.

In my opinion, it's not quite user-friendly for the downstream application. For example, there's a similar issue https://github.com/thu-ml/tianshou/issues/573. Many people (including me) are not in favor of this approach.

@mavenlin could you please state the reason and detail here? I believe it's for speed concerns.

**Comment by Trinkle23897** [comment]
> the first version of EnvPool has two separated threadpool, one for reset and one for step, and that can satisfy the aforementioned requirement.

This is a design choice. two thread pools can be generalized to different reset/step calling patterns, but results in a little lower performance, and the reset/step difference is mainly introduced by gym. However, the internal EnvPool is mainly for dm_control API compatibility. In dm_control, there's no such a big difference and we can utilize only one thread pool to reach the max performance.

Regarding gym: there's also a solution for both upstream (env) and downstream (training) applications. For env, you can set a state that indicate whether it has been reset in the last step or not, and if it is, nothing happens and the environment returns the last step's result; for downstream application,  if it introduces (or assumes) the auto-reset wrapper into vectorized env, there's nothing difference when using this design.

**Comment by mavenlin** [comment]
It was so designed because it simplifies the APIs on both the user end and implementation end, at the sacrifice of some customization. But as far as I see, the case described in this issue is achievable with the current design, the way should be the following (Pseudocode):

```python3
# Async reset, which should return nothing.
envpool.async_reset()

# empty dict that stores the init state of envs
init_states = {} 

while True:
  state = envpool.recv()
  # if it is the first time a env is ever received, set its init state.
  for env_id in state.env_ids:
    if env_id not in init_states:
      init_states[env_id] = state
  # do something else with the state

```

**Comment by LuciusMos** [comment]
> It was so designed because it simplifies the APIs on both the user end and implementation end, at the sacrifice of some customization. But as far as I see, the case described in this issue is achievable with the current design, the way should be the following (Pseudocode):
> 
> ```python
> # Async reset, which should return nothing.
> envpool.async_reset()
> 
> # empty dict that stores the init state of envs
> init_states = {} 
> 
> while True:
>   state = envpool.recv()
>   # if it is the first time a env is ever received, set its init state.
>   for env_id in state.env_ids:
>     if env_id not in init_states:
>       init_states[env_id] = state
>   # do something else with the state
> ```

@mavenlin @Trinkle23897 
Thank you two so much for your response. And my probelem can be solved in this way~
