### ISSUE TITLE
[BUG] no Acc-v3 environment

### ISSUE THREAD

**Issue by 963141377** [sail-sg/envpool#66]
## Describe the bug

When using tianshou, there's no Acc-v3 environment.

  File "test_dqn_acc.py", line 246, in <module>
    Acc_tain()
  File "test_dqn_acc.py", line 112, in Acc_tain
    args.task, num_envs=args.training_num, env_type="gym"
  File "/home/zhulin/.conda/envs/mytorch/lib/python3.7/site-packages/envpool/registration.py", line 43, in make
    f"{task_id} is not supported, `envpool.list_all_envs()` may help."
AssertionError: Acc-v3 is not supported, `envpool.list_all_envs()` may help.

**Comment by Trinkle23897** [comment]
There's no Acc-v3 in either gym or tianshou's example. Is that your customized env?

**Comment by 963141377** [comment]
yes, my cunsomized env. how to add it to envlist?

**Comment by Trinkle23897** [comment]
https://envpool.readthedocs.io/en/latest/pages/env.html

**Comment by 963141377** [comment]
Thank you very much.
