### ISSUE TITLE
[Feature Request] Support wrapper MaxAndSkipEnv for Atari

### ISSUE THREAD

**Issue by LuciusMos** [sail-sg/envpool#68]
## Motivation

For [Atari](https://envpool.readthedocs.io/en/latest/api/atari.html), you provide some built-in wrappers like [OpenAI Baselines](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py). OpenAI Baselines' wrappers include [MaxAndSkipEnv](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py). However I cannot find it in your built-in wrappers.

## Solution

Can you explain why, and whether it is possible to support this wrapper?

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by Trinkle23897** [comment]
MaxAndSkip steps n times and return maximum(obs[-2], obs[-1]). This is implemented in envpool. `frame_skip` argument is for that purpose. https://github.com/sail-sg/envpool/blob/a95e81addf272d7626fa50b7761fe86dc32ee723/envpool/atari/atari_env.h#L185-L200

**Comment by LuciusMos** [comment]
Thank you so much!
