### ISSUE TITLE
[Feature Request] reset -> obs or (obs, info) in gym env

### ISSUE THREAD

**Issue by Trinkle23897** [sail-sg/envpool#89]
This is to support the multi-agent case and adapt to the newest version of gym.
Related issue: https://github.com/thu-ml/tianshou/issues/605

**Comment by jkterry1** [comment]
could you add pettingzoo support in the multiagent case, especially since it's what tianshou is using now?

**Comment by Trinkle23897** [comment]
Sure! Will do.

**Comment by jkterry1** [comment]
pistonball is the one we use as the default for basicaly everything
